/**
 * Email service — sends executive summaries via Nodemailer (SMTP) or Resend.
 */
import nodemailer from 'nodemailer';
import { Resend } from 'resend';
import { config } from '../config/env.js';
import { logger } from '../utils/logger.js';

/**
 * Send the AI-generated executive summary to the recipient.
 *
 * @param {string} recipient - Email address.
 * @param {string} summary   - Markdown summary text.
 */
export async function sendSummaryEmail(recipient, summary) {
  if (config.emailProvider === 'smtp') {
    return sendViaSMTP(recipient, summary);
  } else if (config.emailProvider === 'resend') {
    return sendViaResend(recipient, summary);
  } else {
    throw new Error(`Unsupported email provider: ${config.emailProvider}`);
  }
}

/**
 * Build a styled HTML email from the markdown summary.
 */
function buildHtmlEmail(summaryMarkdown) {
  // Enhanced markdown conversion tailored for email client rendering
  let html = summaryMarkdown
    .replace(/^### (.*$)/gm, '<h3 style="color:#8b5cf6; font-size:18px; margin-top:28px; margin-bottom:12px; font-weight:600; text-transform:uppercase; letter-spacing:0.5px;">$1</h3>')
    .replace(/^## (.*$)/gm, '<h2 style="color:#4c1d95; font-size:22px; border-bottom:1px solid #ede9fe; padding-bottom:12px; margin-top:32px; margin-bottom:16px;">$1</h2>')
    .replace(/^# (.*$)/gm, '<h1 style="color:#4c1d95; font-size:26px; font-weight:700; margin-bottom:20px;">$1</h1>')
    .replace(/\*\*(.*?)\*\*/g, '<strong style="color:#111827; font-weight:700;">$1</strong>')
    .replace(/\*(.*?)\*/g, '<em style="color:#4b5563;">$1</em>')
    .replace(/^- (.*$)/gm, '<li style="margin-bottom:8px; line-height:1.6; color:#374151;">$1</li>')
    .replace(/(<li.*<\/li>\n?)+/g, '<ul style="padding-left:24px; margin-top:12px; margin-bottom:20px;">$&</ul>')
    .replace(/\n{2,}/g, '</p><p style="margin-bottom:16px; line-height:1.7; color:#374151;">')
    .replace(/\n/g, '<br>');

  // Wrap in a sleek, eye-soothing, mobile-responsive layout
  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body style="font-family:'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color:#f5f3ff; margin:0; padding:40px 10px;">
      
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:680px; margin:0 auto; background-color:#ffffff; border-radius:16px; box-shadow:0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -2px rgba(0, 0, 0, 0.05); overflow:hidden;">
        
        <!-- Header -->
        <tr>
          <td style="background-color:#7c3aed; background-image: linear-gradient(135deg, #7c3aed 0%, #ec4899 100%); padding:40px 32px; text-align:center;">
            <div style="font-size:32px; margin-bottom:8px;">🐇</div>
            <h1 style="color:#ffffff; font-size:28px; font-weight:800; margin:0; letter-spacing:-0.5px;">BriefRabbit</h1>
            <p style="color:#ddd6fe; font-size:15px; margin:8px 0 0 0; font-weight:500;">Executive AI Sales Report</p>
          </td>
        </tr>

        <!-- Content Body -->
        <tr>
          <td style="padding:48px 40px;">
            <div style="font-size:16px; color:#374151;">
              <p style="margin-top:0; margin-bottom:16px; line-height:1.7;">${html}</p>
            </div>
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="background-color:#fafafa; border-top:1px solid #ede9fe; padding:24px 40px; text-align:center;">
            <p style="color:#6b7280; font-size:13px; margin:0; line-height:1.5;">
              This report was autonomously generated by <strong>BriefRabbit Analytics</strong>.<br>
              Confidentially delivered via 256-bit encrypted pipeline.
            </p>
          </td>
        </tr>

      </table>
      
    </body>
    </html>`;
}

/**
 * Send via SMTP using Nodemailer.
 */
async function sendViaSMTP(recipient, summary) {
  const isSecure = config.smtpPort === 465;
  
  const transporter = nodemailer.createTransport({
    host: config.smtpHost,
    port: config.smtpPort,
    secure: isSecure,
    auth: {
      user: config.smtpUser,
      pass: config.smtpPassword,
    },
    // Enhanced settings for Port 587 STARTTLS
    requireTLS: !isSecure, 
    connectionTimeout: 30000, 
    greetingTimeout: 30000,
    socketTimeout: 30000,
    tls: {
      // Do not fail on invalid certs (helpful for some cloud relays)
      rejectUnauthorized: false
    }
  });

  // Verify connection configuration
  try {
    await transporter.verify();
    logger.info('SMTP connection verified successfully');
  } catch (err) {
    logger.error(`SMTP verification failed: ${err.message}`);
    throw new Error(`Email verification failed: ${err.message}`);
  }

  await transporter.sendMail({
    from: `"${config.smtpFromName}" <${config.smtpUser}>`,
    to: recipient,
    subject: '📊 Your Executive Sales Summary — BriefRabbit',
    text: summary,
    html: buildHtmlEmail(summary),
  });

  logger.info(`Email sent via SMTP to ${recipient}`);
}

/**
 * Send via Resend API.
 */
async function sendViaResend(recipient, summary) {
  const resend = new Resend(config.resendApiKey);

  await resend.emails.send({
    from: `BriefRabbit <${config.resendFromEmail}>`,
    to: [recipient],
    subject: '📊 Your Executive Sales Summary — BriefRabbit',
    html: buildHtmlEmail(summary),
  });

  logger.info(`Email sent via Resend to ${recipient}`);
}
