/**
 * Swagger/OpenAPI configuration using swagger-jsdoc + swagger-ui-express.
 */
import swaggerJsdoc from 'swagger-jsdoc';
import swaggerUi from 'swagger-ui-express';

const swaggerDefinition = {
  openapi: '3.0.0',
  info: {
    title: 'BriefRabbit API',
    version: '1.0.0',
    description:
      'AI-powered Sales Dataset Analyst & Executive Summary Generator.\n\n' +
      'Upload a CSV/XLSX sales dataset and receive an AI-generated executive summary sent to your email.',
    contact: { name: 'BriefRabbit Team' },
  },
  servers: [
    { url: 'http://localhost:8000', description: 'Local development' },
    { url: 'https://api.briefrabbit.com', description: 'Production' },
  ],
  components: {
    schemas: {
      UploadResponse: {
        type: 'object',
        properties: {
          jobId:              { type: 'string', format: 'uuid', example: '123e4567-e89b-12d3-a456-426614174000' },
          status:             { type: 'string', enum: ['pending', 'processing', 'completed', 'failed'], example: 'pending' },
          message:            { type: 'string', example: 'File accepted. Summary will be sent to email@example.com' },
          estimatedTimeSeconds: { type: 'integer', example: 30 },
        },
      },
      JobStatusResponse: {
        type: 'object',
        properties: {
          jobId:           { type: 'string', format: 'uuid', example: '123e4567-e89b-12d3-a456-426614174000' },
          status:          { type: 'string', enum: ['pending', 'processing', 'completed', 'failed'], example: 'completed' },
          currentStep:     { type: 'string', enum: ['parsing', 'analyzing', 'summarizing', 'emailing', 'email_sent'], example: 'email_sent' },
          progressPercent: { type: 'integer', minimum: 0, maximum: 100, example: 100 },
          createdAt:       { type: 'string', format: 'date-time', example: '2026-03-12T10:00:00Z' },
          completedAt:     { type: 'string', format: 'date-time', nullable: true, example: '2026-03-12T10:00:30Z' },
          summary:         { type: 'string', nullable: true, description: 'Markdown formatted executive summary generated by AI.', example: '## Performance Overview\nRevenue grew by 15%...' },
          error:           { type: 'string', nullable: true, example: null },
        },
      },
      HealthResponse: {
        type: 'object',
        properties: {
          status:   { type: 'string' },
          version:  { type: 'string' },
          services: { type: 'object' },
        },
      },
      ErrorResponse: {
        type: 'object',
        properties: {
          error:   { type: 'string' },
          message: { type: 'string' },
        },
      },
    },
  },
};

const options = {
  swaggerDefinition,
  apis: ['./src/routes/*.js'],  // JSDoc comments in route files
};

const swaggerSpec = swaggerJsdoc(options);

export function setupSwagger(app) {
  app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec, {
    customCss: '.swagger-ui .topbar { display: none }',
    customSiteTitle: 'BriefRabbit API Docs',
  }));

  app.get('/openapi.json', (_req, res) => {
    res.json(swaggerSpec);
  });
}
